# Generated by Django 4.1 on 2022-09-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="movie", old_name="name", new_name="title",),
    ]
